#ifndef GLOBAL_PROTOCOL_ERROR_H
#define GLOBAL_PROTOCOL_ERROR_H

#define GLOBAL_PROTOCOL_ERR_NO_ERROR                0
#define GLOBAL_PROTOCOL_ERR_INVALID_PARAMS          1
#define GLOBAL_PROTOCOL_ERR_ACCOUNT_NOT_EXISTS      2
#define GLOBAL_PROTOCOL_ERR_PASSWORD_INCORRECT      3
#define GLOBAL_PROTOCOL_ERR_REPEAT_LOGIN            4
#define GLOBAL_PROTOCOL_ERR_CONNECT_FAILED          5
#define GLOBAL_PROTOCOL_ERR_DISCONNECTED            6
#define GLOBAL_PROTOCOL_ERR_UNSUPPORTED             7
#define GLOBAL_PROTOCOL_ERR_TARGET_UNREACHABLE      8
#define GLOBAL_PROTOCOL_ERR_TIMEOUT                 9
#define GLOBAL_PROTOCOL_ERR_PATH_UNREACHABLE        10
#define GLOBAL_PROTOCOL_ERR_OPERATE_FAILED          11
#define GLOBAL_PROTOCOL_ERR_ILLEGAL_DATA            12
#define GLOBAL_PROTOCOL_ERR_ACCOUNT_LOCKED          13
#define GLOBAL_PROTOCOL_ERR_ACCOUNT_DISABLED        14
#define GLOBAL_PROTOCOL_ERR_IP_ADDRESS_BLOCKED      15
#define GLOBAL_PROTOCOL_ERR_ACCOUNT_BLOCKED         16
#define GLOBAL_PROTOCOL_ERR_FILE_ALREADY_EXISTS     17
#define GLOBAL_PROTOCOL_ERR_FILE_NOT_EXISTS         18
#define GLOBAL_PROTOCOL_ERR_END_OF_FILE             19
#define GLOBAL_PROTOCOL_ERR_FILE_CLOSED             20

#define GLOBAL_PROTOCOL_ERR_UNKNOW                  -1


namespace Global
{
    namespace Protocol
    {
        const char* formatError(int err);
    }
}


#endif // ERROR_H
